name: (Reausable) Upload Wheel to Test-PyPI and PyPI and test installation

# ----------------------------------------------------------------------------------------------------------------------

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true

# ----------------------------------------------------------------------------------------------------------------------

defaults:
  run:
    shell: bash
    working-directory: .

# ----------------------------------------------------------------------------------------------------------------------

jobs:
  publish-wheel:
    name: Publish Python distribution to the Python package index
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3

      # ----------------------------------------------------------------------------------------------------------------

      - name: Setup python 🐍
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
          cache: pip

      # ----------------------------------------------------------------------------------------------------------------
      - name: Get wheel artifacts 📥
        uses: actions/download-artifact@v4
        with:
          name: pyjpt-wheel
          path: dist/

      # ----------------------------------------------------------------------------------------------------------------

      - name: Setup Graphviz 📊
        uses: ts-graphviz/setup-graphviz@v1

      # ----------------------------------------------------------------------------------------------------------------

      - name: Publish distribution to Test PyPI 📢
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          skip-existing: true
          repository-url: https://test.pypi.org/legacy/

      # ----------------------------------------------------------------------------------------------------------------

      - name: Install wheel from Test PyPI 🛞
        run: >-
          python -m pip install --extra-index-url https://test.pypi.org/simple/ pyjpt==${{ inputs.version }}

      # ----------------------------------------------------------------------------------------------------------------

      - name: Check the installation from Test PyPI ✅
        run: >-
          python -c "import jpt; print(jpt.__version__)"

      # ----------------------------------------------------------------------------------------------------------------

      - name: Publish distribution Version ${{ github.ref_name }} to PyPI 🏁
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip_existing: false
